### ISSUE TITLE
Change the name of the report to rollbar-php-symfony-bundle

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-symfony-bundle#34]
The SDK now supports Symfony 3 and 4.

**Comment by hngl** [comment]
👍

**Comment by ArturMoczulski** [comment]
The package has been renamed to `rollbar-php-symfony-bundle`. Please, update your `composer.json` dependencies.

**Comment by alister** [comment]
Are there any other changes that are required, or additional functionality beyond the name change?

**Comment by ArturMoczulski** [comment]
It should suffice to change the dependency name in `composer.json` and run `composer update`.
