### ISSUE TITLE
Person data not loaded TokenStorage as documented

### ISSUE THREAD

**Issue by hngl** [rollbar/rollbar-php-symfony-bundle#39]
According to [the documentation](https://docs.rollbar.com/docs/symfony#section--person-configuration-option), if the `person` config key is empty/omitted, the Person data should be loaded automatically from the TokenStorage. This does not happen.

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by ArturMoczulski** [comment]
Fixed in `master` and will be included in the upcoming release.
