### ISSUE TITLE
rollbar/rollbar 1.70 is not supported

### ISSUE THREAD

**Issue by rubenvilar** [rollbar/rollbar-php-symfony-bundle#41]
The dependence should change from 

"rollbar/rollbar":"^1" 

to 

"rollbar/rollbar":"1.6.*"

**Comment by jessewgibbs** [comment]
@rubenvilar thanks for bringing this to our attention.

@ArturMoczulski can you please have a look at this?  We may want to fix whatever in rollbar-php 1.7.0 that is making it incompatible with the Symfony bundle.

**Comment by hngl** [comment]
#40

**Comment by ArturMoczulski** [comment]
This was caused by a bug in v1.7.0 and has been now resolved with the rollbar/rollbar-php:v1.7.0 release. Please run composer update in you Symfony app to update to the latest rollbar-php release.
