### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2

### ISSUE THREAD

**Issue by ellisgl** [rollbar/rollbar-php-symfony-bundle#49]
In Symfony 4.2, there's a deprecation warning of:
A tree builder without a root node is deprecated since Symfony 4.2

Looks like a simple fix:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/594/commits/7db9568f59fbc0411f3d816393d90be2d4cccb82

**Comment by mwidner** [comment]
Yes, please accept this PR. I get tired of seeing deprecation warnings like this that I can do nothing about.
