### ISSUE TITLE
Update tag from 3.1.2 to 3.1.3?

### ISSUE THREAD

**Issue by ellisgl** [rollbar/rollbar-php-symfony-bundle#58]
I noticed the last merge into master (my fix) wasn't tagged, so everyone is stuck with the previous version.

**Comment by anthropos9** [comment]
Symfony 4.4 is now complaining about the TreeBuilder deprecation. If we could get a release with that fix sooner than later that'd be great.

**Comment by ellisgl** [comment]
5.0 will totally break.

**Comment by jbroutier** [comment]
Bump. The bundle is now unusable due to Symfony 5 BCs...

**Comment by mwidner** [comment]
Very much would like to see this merged in. It's blocking our ability to upgrade to Symfony 5.

**Comment by eman1986** [comment]
I'd like to see a fix soon too, I've taken out rollbar support from my code and I'd like to bring it back in.

**Comment by Dyachenko** [comment]
Hi I've updated bundle to be able to use it with Symfony 5 and also bumped PHP version to >7.1
https://github.com/rollbar/rollbar-php-symfony-bundle/pull/61
it works for me with Symfony 5 
if somebody also  could test, it would be perfect

**Comment by ArturMoczulski** [comment]
The tag `v4.0.0` is out with Symfony5 support here: https://github.com/rollbar/rollbar-php-symfony-bundle/releases/tag/v4.0.0

**Comment by ellisgl** [comment]
v4.0.0 has BC breaking changes with 4.x.... My PR made it compatible with both.
