### ISSUE TITLE
Does not support transformer option

### ISSUE THREAD

**Issue by Bilge** [rollbar/rollbar-php-symfony-bundle#65]
According to the [configuration reference](https://docs.rollbar.com/docs/php-configuration-reference) there should be an option to assign a `transformer` class. However, attempting to set this option emits the following error.

>In ArrayNode.php line 326:
>
>  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "transformer" under "rollbar". Available options are "access_token", "agent_log_location", "allow_exec", "autodetect_branch", "base_api_url", "branch", "capture_email", "capture_error_stacktraces", "capture_ip",
  "capture_username", "check_ignore", "code_version", "custom", "custom_data_method", "custom_truncation", "enabled", "endpoint", "environment", "error_sample_rates", "exception_sample_rates", "fluent_host", "fluent_port", "fluent_tag
  ", "handler", "host", "include_error_code_context", "include_exception_code_context", "include_raw_request_body", "included_errno", "local_vars_dump", "log_payload", "log_payload_logger", "max_items", "max_nesting_depth", "minimum_l
  evel", "person", "person_fn", "proxy", "raise_on_error", "report_suppressed", "root", "scrub_fields", "scrub_whitelist", "send_message_trace", "timeout", "transmit", "use_error_reporting", "verbose", "verbose_logger".

**Comment by art-cg** [comment]
It would be great to have this feature

**Comment by bxsx** [comment]
@Bilge @art-cg @danielroehrig 

This issue is fixed in https://github.com/rollbar/rollbar-php/pull/543 and it's already merged into master.
Thanks, @danielroehrig for the contribution! 🎉

**Comment by art-cg** [comment]
Thanks
