### ISSUE TITLE
A new branch for Symfony 4 + PHP 7 + rollbar-php v2

### ISSUE THREAD

**Issue by thekordy** [rollbar/rollbar-php-symfony-bundle#67]
Hi, The current branch symfony_3_4 is supposed to support both symfony 3 and symfony 4 together. And that causes many issues as an example it can't support rollbar-php v2, in the meantime symfony 4 has still many years to come and many requirements in future will break the support of symfony 3.

Therefor, I'd suggest to seperate that branch symfony_3_4 to two branches symfony_3 and symfony_4, so it would be much easier to keep up with rollbar-php and maintain symfony 4 support.

**Comment by danielmorell** [comment]
This issue is pretty old. And we are not currently putting a lot of resources into developing new features on the Symfony 3 and 4 branches. This is probably not a need at the current time. I am going to close this issue for now. If it becomes a problem we can reopen or address it at that point.
