### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by Bilge** [rollbar/rollbar-php-symfony-bundle#75]
Since this library relies on `rollbar:^2`, and does not permit v3, upstream compatibility is blocking PHP 8.1 upgrades. However, it appears that at this time, even v3 does not yet fix the issue, as documented at rollbar/rollbar-php#555. Nevertheless, v3 compatibility should be desired so PHP 8.1 compatibility can be leveraged when it is available.

**Comment by art-cg** [comment]
V3 would be solved by https://github.com/rollbar/rollbar-php-symfony-bundle/pull/73/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R31

The depreaction message (This is not an error) schould be handled in the linked repo.

**Comment by janicekt** [comment]
I try on PHP 8.1.1. with symfony 5.4.9 and version v5.0.0-RC1 works ok ;)

**Comment by janicekt** [comment]
@danielmorell  🔝

**Comment by danielmorell** [comment]
With the release of stable v5.0.0 this should be safe to close.
