### ISSUE TITLE
Symfony ^6.0 compatibility

### ISSUE THREAD

**Issue by armetiz** [rollbar/rollbar-php-symfony-bundle#76]
Hi there.

I hope that rollbar will be compatible with Symfony ^6.0.

Regards,

**Comment by elliotjreed** [comment]
I would second this request! For now it is possible to use the `rollbar/rollbar` PHP package (`composer require rollbar/rollbar`) and use Monolog's Rollbar handler.

In your `services.yaml` you can do

**Comment by art-cg** [comment]
@armetiz Please see related PR https://github.com/rollbar/rollbar-php-symfony-bundle/pull/73

**Comment by janicekt** [comment]
I try on PHP 8.1.1. with symfony 5.4.9 and version v5.0.0-RC1 works ok ;)

**Comment by apphancer** [comment]
@danielmorell I am using v5.0.0-RC1 and happy with how it's performing with a few of my projects. Looking forward to seeing the stable release.

**Comment by danielmorell** [comment]
Hi @nielsmouthaan I am looking at 07/25/22 or 08/01/22.

**Comment by YaHkO** [comment]
Hi, @danielmorell  any news ?

**Comment by danielmorell** [comment]
Sorry for the delay. We wanted to double check our work, and it took longer than we were hoping. We released `v5.0.0` today.
