### ISSUE TITLE
5.0.0 tag is not on Packagist

### ISSUE THREAD

**Issue by Bilge** [rollbar/rollbar-php-symfony-bundle#83]
[According to Packagist](https://packagist.org/packages/rollbar/rollbar-php-symfony-bundle), the latest tag is still the RC, `v5.0.0-RC1` published at 2022-05-16 21:21 UTC. This is despite the fact that the tag was pushed 19 hours ago, which is more than enough time for Packagist to sync.

Also, whilst I'm here, I may as well point out that, according to [your changelog](https://github.com/rollbar/rollbar-php-symfony-bundle/blob/3ce351320502a1e42f2be909c89a5b585e497c84/CHANGELOG.md), v5.0.0 was released on 2019-01-02 (almost 4 years ago).

**Comment by Chris53897** [comment]
Look like it is published in the meantime. @Bilge Can this issue be closed? 
https://packagist.org/packages/rollbar/rollbar-php-symfony-bundle#v5.0.0
