### ISSUE TITLE
Symfony 7 Compatibility

### ISSUE THREAD

**Issue by henrythethird** [rollbar/rollbar-php-symfony-bundle#94]
Do you already have plans to implement Symfony 7 compatibility?

**Comment by henrythethird** [comment]
There's already a merge request https://github.com/rollbar/rollbar-php-symfony-bundle/pull/95

**Comment by zdavis-rollbar** [comment]
@henrythethird  are you interested in becoming a maintainer or an owner of this repo?  We are looking for more community support so you aren't constantly waiting on us.

**Comment by danielmorell** [comment]
This has been resolved by #95.
